import { chromium } from "@playwright/test";
const base = process.env.BASE ?? "http://localhost:3000";
const out = process.argv[2] ?? "/tmp/claude-0/flow";
const device = process.argv[3] ?? "desktop";
import fs from "node:fs";
fs.mkdirSync(out, { recursive: true });
const browser = await chromium.launch({ executablePath: process.env.CHROME_PATH ?? "/opt/pw-browsers/chromium-1194/chrome-linux/chrome" });
const ctx = await browser.newContext(device === "mobile" ? { viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true } : { viewport: { width: 1360, height: 900 } });
const page = await ctx.newPage();
const errors = [];
page.on("pageerror", (e) => errors.push(e.message));
page.on("console", (m) => m.type() === "error" && !m.text().includes("TUNNEL") && errors.push(m.text()));
let n = 0;
const shot = async (name) => page.screenshot({ path: `${out}/${String(++n).padStart(2, "0")}-${name}-${device}.png`, fullPage: false });

await page.goto(`${base}/studio-lune-nails`);
await page.getByRole("link", { name: /^Book / }).first().click();
await page.waitForURL(/\/book/);
await page.waitForTimeout(800);
await shot("options");
await page.getByRole("radio", { name: /^Long/ }).click();
await page.getByRole("radio", { name: /^Almond/ }).click();
await page.getByRole("radio", { name: /^French/ }).click();
await shot("options-selected");
await page.getByRole("button", { name: "Continue" }).last().click();
await page.waitForTimeout(500);
await shot("who");
await page.getByRole("button", { name: "Continue" }).last().click();
await page.waitForTimeout(1500);
await shot("time");
const slot = page.locator('[role="radiogroup"] [role="radio"]').first();
await slot.click();
await page.waitForTimeout(400);
console.log("slot checked:", await slot.getAttribute("aria-checked"), await slot.textContent());
await shot("time-selected");
await page.getByRole("button", { name: "Continue" }).last().click();
await page.waitForTimeout(500);
await shot("details");
await page.getByRole("radio", { name: "No" }).click();
await page.getByRole("button", { name: "Continue" }).last().click();
await page.waitForTimeout(1500);
await shot("review-signed-out");
// inline signup
const email = `flow${Date.now()}@example.com`;
await page.getByLabel("Full name").fill("Robin Flow");
await page.getByLabel("Email").fill(email);
await page.getByLabel("Password").fill("a-strong-passphrase");
await page.getByRole("button", { name: /Create account & continue/ }).click();
await page.waitForTimeout(2500);
await shot("review-signed-in");
await page.getByRole("button", { name: /Confirm booking|Confirm$/ }).last().click();
await page.waitForURL(/\/bookings\/.+new=1/, { timeout: 20000 });
await page.waitForTimeout(800);
await page.screenshot({ path: `${out}/${String(++n).padStart(2, "0")}-confirmation-${device}.png`, fullPage: true });
console.log("booked:", page.url());
console.log(errors.length ? "ERRORS:\n" + errors.join("\n") : "no errors");
await browser.close();
